#!/bin/sh

if [ "$1" == "stop" ]
then
    tmux send-keys -t minecraft 'say SERVER SHUTTING DOWN. Saving map...' C-m 'save-all' C-m 'stop' C-m
    sleep 15
fi

if [ "$1" == "save-on" ]
then
    tmux send-keys -t minecraft 'save-on' C-m 'say Backup complete!' C-m
fi

if [ "$1" == "save-off" ]
then
    tmux send-keys -t minecraft 'say Backup process starting...' C-m 'save-off' C-m 'save-all' C-m
fi

